export const bingoDescriptor = {
	data: [
		'Wymień trzy rzeczy, które kochasz robić w wolnym czasie.',
		'Jaka jest Twoja ulubiona pora roku. Opisz dlaczego?',
		'Zachęć kilka osób żeby z Tobą klaskały przez 15 sekund.',
		'Powiedz dzień dobry lub cześć 3 nieznanym osobom.',
		'Zatańcz do swojego ulubionego utworu.',
		'Jakie są Twoje trzy największe marzenia?',
		'Wymień dwa utwory muzyczne, które wprawiają Cię w dobry nastrój. Możesz je zanucić.',
		'Trzy miejsca na ziemi, jakie chciałabyś/chciałbyś odwiedzić.',
		'Poleć wybranej osobie miejsce, gdzie czułaś/eś się najbardziej zrelaksowany.',
		'Zastanów się jakie Twoje zdolności wzbudzają u innych podziw. Wymień przynajmniej dwie!',
		'Opisz sytuację, w której byłaś/eś z siebie dumny.',
		'Co ostatnio stworzyłaś/eś? I jest to wyłącznie Twoje dzieło?',
		'Dobry nastrój!!!',
		'Wymień swoje trzy mocne strony charakteru.',
		'Najlepszy dzień Twojego życia.',
		'Napisz do bliskiej Ci osoby miłą wiadomość.',
		'Twoje hobby?',
		'Powiedz coś miłego wybranej osobie.',
		'Powiedz coś miłego osobie po Twojej prawej stronie.',
		'Co Cię najbardziej bawi, śmieszy?',
		'Powiedz coś  miłego osobie po Twojej lewej stronie.',
		'Opisz dzień, kiedy czułaś/eś się naprawdę zakochana/ny',
		'Opisz sytuację w której czułaś/eś się naprawdę szczęśliwa/y',
		'Osobie znajdującej się obok Ciebie pokaż bez słów co najbardziej lubisz robić.',
		'Opisz sytuację, w której czułaś/eś się naprawdę pewna/y siebie.',
	],
	dimensions: {
		width: 5,
		height: 5,
	},
};
Object.freeze(bingoDescriptor);
